// <auto-generated />
using ChronoClashDeckBuilder.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChronoClashDeckBuilder.Migrations
{
    [DbContext(typeof(ChronoClashDbContext))]
    partial class ChronoClashDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChronoClashDeckBuilder.Models.CardModel", b =>
                {
                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CardAbilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CardCost")
                        .HasColumnType("int");

                    b.Property<string>("CardImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardStackAbilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CardStrength")
                        .HasColumnType("int");

                    b.Property<string>("CardType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardNumber");

                    b.ToTable("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
